// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>

using MaskingSocialApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MaskingSocialApp.Data.Configurations
{
    public partial class TaxpayerConfiguration : IEntityTypeConfiguration<Taxpayer>
    {
        public void Configure(EntityTypeBuilder<Taxpayer> entity)
        {
            entity.Property(e => e.SocialSecurityNumber)
            .HasMaxLength(9)
            .IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Taxpayer> entity);
    }
}
