// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SqlLiteSample2.Interfaces;

namespace SqlLiteSample2.Models;

public partial class Contacts : IPerson
{
    public int ContactId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int? ContactTypeIdentifier { get; set; }

    public string FullName { get; set; }

    public virtual ICollection<ContactDevices> ContactDevices { get; set; } = new List<ContactDevices>();

    public virtual ContactType ContactTypeIdentifierNavigation { get; set; }

    public virtual ICollection<Customers> Customers { get; set; } = new List<Customers>();
}