// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SqlLiteSample2.Models;

public partial class Orders
{
    public int OrderID { get; set; }

    public int? CustomerIdentifier { get; set; }

    public int? EmployeeID { get; set; }

    public DateTime OrderDate { get; set; }

    public DateTime RequiredDate { get; set; }

    public DateTime ShippedDate { get; set; }

    public DateTime DeliveredDate { get; set; }

    public int? ShipVia { get; set; }

    public double? Freight { get; set; }

    public string ShipAddress { get; set; }

    public string ShipCity { get; set; }

    public string ShipRegion { get; set; }

    public string ShipPostalCode { get; set; }

    public string ShipCountry { get; set; }

    public virtual Customers CustomerIdentifierNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual ICollection<OrderDetails> OrderDetails { get; set; } = new List<OrderDetails>();

    public virtual Shippers ShipViaNavigation { get; set; }
}