// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace ContactsDataLibrary.Models;

public partial class AddressType
{
    public byte AddressTypeId { get; set; }

    public string AddressTypeName { get; set; }

    public virtual ICollection<PersonAddress> PersonAddresses { get; set; } = new List<PersonAddress>();
}