// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MaskingSocialApp.Models;

public partial class Taxpayer
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string SocialSecurityNumber { get; set; }
    public string PhoneNumber { get; set; }
}