// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SqlLiteSample2.Data;
using SqlLiteSample2.Models;
using System;
using System.Collections.Generic;

namespace SqlLiteSample2.Data.Configurations
{
    public partial class ContactDevicesConfiguration : IEntityTypeConfiguration<ContactDevices>
    {
        public void Configure(EntityTypeBuilder<ContactDevices> entity)
        {
            entity.HasKey(e => e.ContactDeviceId);

            entity.HasIndex(e => e.ContactId, "ContactDevices_IX_ContactDevices_ContactId").IsDescending();

            entity.HasIndex(e => e.PhoneTypeIdentifier, "ContactDevices_IX_ContactDevices_PhoneTypeIdentifier").IsDescending();

            entity.Property(e => e.PhoneNumber)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar");

            entity.HasOne(d => d.Contact).WithMany(p => p.ContactDevices).HasForeignKey(d => d.ContactId);

            entity.HasOne(d => d.PhoneTypeIdentifierNavigation).WithMany(p => p.ContactDevices).HasForeignKey(d => d.PhoneTypeIdentifier);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactDevices> entity);
    }
}
