// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SqlLiteSample2.Data;
using SqlLiteSample2.Models;
using System;
using System.Collections.Generic;

namespace SqlLiteSample2.Data.Configurations
{
    public partial class ContactsConfiguration : IEntityTypeConfiguration<Contacts>
    {
        public void Configure(EntityTypeBuilder<Contacts> entity)
        {
            entity.HasKey(e => e.ContactId);

            entity.HasIndex(e => e.ContactTypeIdentifier, "Contacts_IX_Contacts_ContactTypeIdentifier").IsDescending();

            entity.Property(e => e.FirstName)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar");
            entity.Property(e => e.FullName)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar");
            entity.Property(e => e.LastName)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar");

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Contacts).HasForeignKey(d => d.ContactTypeIdentifier);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Contacts> entity);
    }
}
