// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SqlLiteSample2.Data;
using SqlLiteSample2.Models;
using System;
using System.Collections.Generic;

namespace SqlLiteSample2.Data.Configurations
{
    public partial class CustomersConfiguration : IEntityTypeConfiguration<Customers>
    {
        public void Configure(EntityTypeBuilder<Customers> entity)
        {
            entity.HasKey(e => e.CustomerIdentifier);

            entity.HasIndex(e => e.City, "Customers_City").IsDescending();

            entity.HasIndex(e => e.CompanyName, "Customers_CompanyName").IsDescending();

            entity.HasIndex(e => e.ContactId, "Customers_IX_Customers_ContactId").IsDescending();

            entity.HasIndex(e => e.ContactTypeIdentifier, "Customers_IX_Customers_ContactTypeIdentifier").IsDescending();

            entity.HasIndex(e => e.CountryIdentifier, "Customers_IX_Customers_CountryIdentifier").IsDescending();

            entity.HasIndex(e => e.PostalCode, "Customers_PostalCode").IsDescending();

            entity.HasIndex(e => e.Region, "Customers_Region").IsDescending();

            entity.Property(e => e.City)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(15)");
            entity.Property(e => e.CompanyName)
            .IsRequired()
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(40)");
            entity.Property(e => e.Fax)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(24)");
            entity.Property(e => e.ModifiedDate)
            .HasDefaultValueSql("CURRENT_TIMESTAMP")
            .UseCollation("NOCASE")
            .HasColumnType("datetime");
            entity.Property(e => e.Phone)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(24)");
            entity.Property(e => e.PostalCode)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(10)");
            entity.Property(e => e.Region)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(15)");
            entity.Property(e => e.Street)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(60)");

            entity.HasOne(d => d.Contact).WithMany(p => p.Customers).HasForeignKey(d => d.ContactId);

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Customers).HasForeignKey(d => d.ContactTypeIdentifier);

            entity.HasOne(d => d.CountryIdentifierNavigation).WithMany(p => p.Customers).HasForeignKey(d => d.CountryIdentifier);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Customers> entity);
    }
}
