// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SqlLiteSample2.Data;
using SqlLiteSample2.Models;
using System;
using System.Collections.Generic;

namespace SqlLiteSample2.Data.Configurations
{
    public partial class EmployeesConfiguration : IEntityTypeConfiguration<Employees>
    {
        public void Configure(EntityTypeBuilder<Employees> entity)
        {
            entity.HasKey(e => e.EmployeeID);

            entity.HasIndex(e => e.ContactTypeIdentifier, "Employees_IX_Employees_ContactTypeIdentifier").IsDescending();

            entity.HasIndex(e => e.CountryIdentifier, "Employees_IX_Employees_CountryIdentifier").IsDescending();

            entity.HasIndex(e => e.ReportsToNavigationEmployeeID, "Employees_IX_Employees_ReportsToNavigationEmployeeID").IsDescending();

            entity.Property(e => e.Address)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(60)");
            entity.Property(e => e.BirthDate).HasColumnType("datetime");
            entity.Property(e => e.City)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(15)");
            entity.Property(e => e.Extension)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(4)");
            entity.Property(e => e.FirstName)
            .IsRequired()
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(10)");
            entity.Property(e => e.FullName)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(57)");
            entity.Property(e => e.HireDate).HasColumnType("datetime");
            entity.Property(e => e.HomePhone)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(24)");
            entity.Property(e => e.LastName)
            .IsRequired()
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(20)");
            entity.Property(e => e.Notes)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar");
            entity.Property(e => e.PostalCode)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(10)");
            entity.Property(e => e.Region)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(15)");
            entity.Property(e => e.TitleOfCourtesy)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(25)");

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Employees).HasForeignKey(d => d.ContactTypeIdentifier);

            entity.HasOne(d => d.CountryIdentifierNavigation).WithMany(p => p.Employees).HasForeignKey(d => d.CountryIdentifier);

            entity.HasOne(d => d.ReportsToNavigationEmployee).WithMany(p => p.InverseReportsToNavigationEmployee).HasForeignKey(d => d.ReportsToNavigationEmployeeID);

            entity.HasMany(d => d.Territory).WithMany(p => p.Employee)
            .UsingEntity<Dictionary<string, object>>(
                "EmployeeTerritories",
                r => r.HasOne<Territories>().WithMany()
                    .HasForeignKey("TerritoryID")
                    .OnDelete(DeleteBehavior.ClientSetNull),
                l => l.HasOne<Employees>().WithMany()
                    .HasForeignKey("EmployeeID")
                    .OnDelete(DeleteBehavior.ClientSetNull),
                j =>
                {
                    j.HasKey("EmployeeID", "TerritoryID");
                    j.HasIndex(new[] { "TerritoryID" }, "EmployeeTerritories_IX_EmployeeTerritories_TerritoryID").IsDescending();
                    j.IndexerProperty<string>("TerritoryID")
                        .UseCollation("NOCASE")
                        .HasColumnType("nvarchar(20)");
                });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employees> entity);
    }
}
