// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SqlLiteSample2.Data;
using SqlLiteSample2.Models;
using System;
using System.Collections.Generic;

namespace SqlLiteSample2.Data.Configurations
{
    public partial class ProductsConfiguration : IEntityTypeConfiguration<Products>
    {
        public void Configure(EntityTypeBuilder<Products> entity)
        {
            entity.HasKey(e => e.ProductID);

            entity.HasIndex(e => e.CategoryID, "Products_IX_Products_CategoryID").IsDescending();

            entity.HasIndex(e => e.SupplierID, "Products_IX_Products_SupplierID").IsDescending();

            entity.Property(e => e.Discontinued).HasColumnType("bit");
            entity.Property(e => e.DiscontinuedDate)
            .UseCollation("NOCASE")
            .HasColumnType("datetime");
            entity.Property(e => e.ProductName)
            .IsRequired()
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(40)");
            entity.Property(e => e.QuantityPerUnit)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(20)");
            entity.Property(e => e.ReorderLevel).HasColumnType("smallint");
            entity.Property(e => e.UnitPrice).HasColumnType("numeric");
            entity.Property(e => e.UnitsInStock).HasColumnType("smallint");
            entity.Property(e => e.UnitsOnOrder).HasColumnType("smallint");

            entity.HasOne(d => d.Category).WithMany(p => p.Products).HasForeignKey(d => d.CategoryID);

            entity.HasOne(d => d.Supplier).WithMany(p => p.Products).HasForeignKey(d => d.SupplierID);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Products> entity);
    }
}
