// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SqlLiteSample2.Data;
using SqlLiteSample2.Models;
using System;
using System.Collections.Generic;

namespace SqlLiteSample2.Data.Configurations
{
    public partial class TerritoriesConfiguration : IEntityTypeConfiguration<Territories>
    {
        public void Configure(EntityTypeBuilder<Territories> entity)
        {
            entity.HasKey(e => e.TerritoryID);

            entity.HasIndex(e => e.RegionID, "Territories_IX_Territories_RegionID").IsDescending();

            entity.Property(e => e.TerritoryID)
            .UseCollation("NOCASE")
            .HasColumnType("nvarchar(20)");
            entity.Property(e => e.TerritoryDescription)
            .IsRequired()
            .UseCollation("NOCASE")
            .HasColumnType("char(50)");

            entity.HasOne(d => d.Region).WithMany(p => p.Territories)
            .HasForeignKey(d => d.RegionID)
            .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Territories> entity);
    }
}
