// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

public partial class BusinessEntityPhone
{
    public int BusinessEntityPhoneID { get; set; }

    public string PhoneNumber { get; set; }

    public int? PhoneNumberTypeID { get; set; }

    public DateTime? ModifiedDate { get; set; }
}