// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CategoriesApplication1.Models;

public partial class Categories
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Ext { get; set; }

    public string AltText { get; set; }

    public byte[] Photo { get; set; }
}