// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NorthWindSqlLiteApp1.Models;

public partial class Categories
{
    public int CategoryID { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public byte[] Picture { get; set; }

    public byte[] Photo { get; set; }

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();
}