// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SqlLiteSampleComputedColumns.Models;

namespace SqlLiteSampleComputedColumns.Data;

public partial class COEDDotnetLandVS2022WritingSqlTipsSqlLiteSampleComputedColumnsSample1dbContext : DbContext
{
    public COEDDotnetLandVS2022WritingSqlTipsSqlLiteSampleComputedColumnsSample1dbContext()
    {
    }

    public COEDDotnetLandVS2022WritingSqlTipsSqlLiteSampleComputedColumnsSample1dbContext(DbContextOptions<COEDDotnetLandVS2022WritingSqlTipsSqlLiteSampleComputedColumnsSample1dbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Person> Person { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlite("Data Source=Sample1.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>(entity =>
        {
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasColumnType("TEXT (50)");
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasColumnType("TEXT (50)");
            entity.Property(e => e.Pin).HasColumnType("INTEGER (5)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}