// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductsCategoriesApp.Models;

[Index("ContactId", Name = "IX_ContactDevices_ContactId")]
[Index("PhoneTypeIdentifier", Name = "IX_ContactDevices_PhoneTypeIdentifier")]
public partial class ContactDevices
{
    [Key]
    public int id { get; set; }

    public int? ContactId { get; set; }

    public int? PhoneTypeIdentifier { get; set; }

    public string PhoneNumber { get; set; }

    [ForeignKey("ContactId")]
    [InverseProperty("ContactDevices")]
    public virtual Contacts Contact { get; set; }

    [ForeignKey("PhoneTypeIdentifier")]
    [InverseProperty("ContactDevices")]
    public virtual PhoneType PhoneTypeIdentifierNavigation { get; set; }
}