// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductsCategoriesApp.Models;

public partial class Countries
{
    [Key]
    public int CountryIdentifier { get; set; }

    public string Name { get; set; }

    [InverseProperty("CountryIdentifierNavigation")]
    public virtual ICollection<Customers> Customers { get; } = new List<Customers>();

    [InverseProperty("CountryIdentifierNavigation")]
    public virtual ICollection<Employees> Employees { get; } = new List<Employees>();

    [InverseProperty("CountryIdentifierNavigation")]
    public virtual ICollection<Suppliers> Suppliers { get; } = new List<Suppliers>();
}