// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductsCategoriesApp.Models;

[Index("ContactTypeIdentifier", Name = "IX_Employees_ContactTypeIdentifier")]
[Index("CountryIdentifier", Name = "IX_Employees_CountryIdentifier")]
[Index("ReportsToNavigationEmployeeID", Name = "IX_Employees_ReportsToNavigationEmployeeID")]
public partial class Employees
{
    [Key]
    public int EmployeeID { get; set; }

    [Required]
    [StringLength(20)]
    public string LastName { get; set; }

    [Required]
    [StringLength(10)]
    public string FirstName { get; set; }

    public int? ContactTypeIdentifier { get; set; }

    [StringLength(25)]
    public string TitleOfCourtesy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BirthDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? HireDate { get; set; }

    [StringLength(60)]
    public string Address { get; set; }

    [StringLength(15)]
    public string City { get; set; }

    [StringLength(15)]
    public string Region { get; set; }

    [StringLength(10)]
    public string PostalCode { get; set; }

    public int? CountryIdentifier { get; set; }

    [StringLength(24)]
    public string HomePhone { get; set; }

    [StringLength(4)]
    public string Extension { get; set; }

    public string Notes { get; set; }

    public int? ReportsTo { get; set; }

    public int? ReportsToNavigationEmployeeID { get; set; }

    [ForeignKey("ContactTypeIdentifier")]
    [InverseProperty("Employees")]
    public virtual ContactType ContactTypeIdentifierNavigation { get; set; }

    [ForeignKey("CountryIdentifier")]
    [InverseProperty("Employees")]
    public virtual Countries CountryIdentifierNavigation { get; set; }

    [InverseProperty("ReportsToNavigationEmployee")]
    public virtual ICollection<Employees> InverseReportsToNavigationEmployee { get; } = new List<Employees>();

    [InverseProperty("Employee")]
    public virtual ICollection<Orders> Orders { get; } = new List<Orders>();

    [ForeignKey("ReportsToNavigationEmployeeID")]
    [InverseProperty("InverseReportsToNavigationEmployee")]
    public virtual Employees ReportsToNavigationEmployee { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Employee")]
    public virtual ICollection<Territories> Territory { get; } = new List<Territories>();
}