// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductsCategoriesApp.Models;

[Index("CustomerIdentifier", Name = "IX_Orders_CustomerIdentifier")]
[Index("EmployeeID", Name = "IX_Orders_EmployeeID")]
[Index("ShipVia", Name = "IX_Orders_ShipVia")]
public partial class Orders
{
    [Key]
    public int OrderID { get; set; }

    public int? CustomerIdentifier { get; set; }

    public int? EmployeeID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? OrderDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RequiredDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ShippedDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DeliveredDate { get; set; }

    public int? ShipVia { get; set; }

    [Column(TypeName = "decimal(19, 2)")]
    public decimal? Freight { get; set; }

    [StringLength(60)]
    public string ShipAddress { get; set; }

    [StringLength(15)]
    public string ShipCity { get; set; }

    [StringLength(15)]
    public string ShipRegion { get; set; }

    [StringLength(10)]
    public string ShipPostalCode { get; set; }

    [StringLength(15)]
    public string ShipCountry { get; set; }

    [ForeignKey("CustomerIdentifier")]
    [InverseProperty("Orders")]
    public virtual Customers CustomerIdentifierNavigation { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("Orders")]
    public virtual Employees Employee { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetails> OrderDetails { get; } = new List<OrderDetails>();

    [ForeignKey("ShipVia")]
    [InverseProperty("Orders")]
    public virtual Shippers ShipViaNavigation { get; set; }
}