// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductsCategoriesApp.Models;

[PrimaryKey("OrderID", "ProductID")]
[Index("ProductID", Name = "IX_OrderDetails_ProductID")]
public partial class OrderDetails
{
    [Key]
    public int OrderID { get; set; }

    [Key]
    public int ProductID { get; set; }

    [Column(TypeName = "decimal(19, 2)")]
    public decimal UnitPrice { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(19, 2)")]
    public decimal Discount { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("OrderDetails")]
    public virtual Orders Order { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("OrderDetails")]
    public virtual Products Product { get; set; }
}