// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProductsCategoriesApp.Models;

public partial class PhoneType
{
    [Key]
    [Column("PhoneTypeIdenitfier")]
    public int PhoneTypeIdentifier { get; set; }

    public string PhoneTypeDescription { get; set; }

    [InverseProperty("PhoneTypeIdentifierNavigation")]
    public virtual ICollection<ContactDevices> ContactDevices { get; } = new List<ContactDevices>();
}