// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductsCategoriesApp.Models;

public partial class PhoneType
{
    [Key]
    public int PhoneTypeIdenitfier { get; set; }

    public string PhoneTypeDescription { get; set; }

    [InverseProperty("PhoneTypeIdentifierNavigation")]
    public virtual ICollection<ContactDevices> ContactDevices { get; } = new List<ContactDevices>();
}