// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductsCategoriesApp.Models;

[Index("CategoryID", Name = "IX_Products_CategoryID")]
[Index("SupplierID", Name = "IX_Products_SupplierID")]
public partial class Products
{
    [Key]
    public int ProductID { get; set; }

    [Required]
    [StringLength(40)]
    public string ProductName { get; set; }

    public int? SupplierID { get; set; }

    public int? CategoryID { get; set; }

    [StringLength(20)]
    public string QuantityPerUnit { get; set; }

    [Column(TypeName = "decimal(19, 2)")]
    public decimal? UnitPrice { get; set; }

    public int? UnitsInStock { get; set; }

    public int? UnitsOnOrder { get; set; }

    public int? ReorderLevel { get; set; }

    public bool Discontinued { get; set; }

    public DateTime? DiscontinuedDate { get; set; }

    [ForeignKey("CategoryID")]
    [InverseProperty("Products")]
    public virtual Categories Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<OrderDetails> OrderDetails { get; } = new List<OrderDetails>();

    [ForeignKey("SupplierID")]
    [InverseProperty("Products")]
    public virtual Suppliers Supplier { get; set; }

    public override string ToString() => ProductName;

}