// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProductsCategoriesApp.Models;

[Index("CountryIdentifier", Name = "IX_Suppliers_CountryIdentifier")]
public partial class Suppliers
{
    [Key]
    public int SupplierID { get; set; }

    [Required]
    [StringLength(40)]
    public string CompanyName { get; set; }

    [StringLength(30)]
    public string ContactName { get; set; }

    [StringLength(30)]
    public string ContactTitle { get; set; }

    [StringLength(60)]
    public string Street { get; set; }

    [StringLength(15)]
    public string City { get; set; }

    [StringLength(15)]
    public string Region { get; set; }

    public int RegionId { get; set; }

    [StringLength(10)]
    public string PostalCode { get; set; }

    public int? CountryIdentifier { get; set; }

    [StringLength(24)]
    public string Phone { get; set; }

    [StringLength(24)]
    public string Fax { get; set; }

    [Column(TypeName = "ntext")]
    public string HomePage { get; set; }

    [ForeignKey("CountryIdentifier")]
    [InverseProperty("Suppliers")]
    public virtual Countries CountryIdentifierNavigation { get; set; }

    [InverseProperty("Supplier")]
    public virtual ICollection<Products> Products { get; } = new List<Products>();

    [ForeignKey("RegionId")]
    [InverseProperty("Suppliers")]
    public virtual SupplierRegion RegionNavigation { get; set; }
}