// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ConsoleConfigurationLibrary.Classes;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NorthWindSqlLiteApp1.Classes;
using NorthWindSqlLiteApp1.Classes.Configuration;
using NorthWindSqlLiteApp1.Classes.Core;
using NorthWindSqlLiteApp1.Classes.Interceptor;
using NorthWindSqlLiteApp1.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace NorthWindSqlLiteApp1.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<ContactDevices> ContactDevices { get; set; }

    public virtual DbSet<ContactType> ContactType { get; set; }

    public virtual DbSet<Contacts> Contacts { get; set; }

    public virtual DbSet<Countries> Countries { get; set; }

    public virtual DbSet<Customers> Customers { get; set; }

    public virtual DbSet<Employees> Employees { get; set; }

    public virtual DbSet<OrderDetails> OrderDetails { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<PhoneType> PhoneType { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<Region> Region { get; set; }

    public virtual DbSet<Shippers> Shippers { get; set; }

    public virtual DbSet<SupplierRegion> SupplierRegion { get; set; }

    public virtual DbSet<Suppliers> Suppliers { get; set; }

    public virtual DbSet<Territories> Territories { get; set; }

    /// <summary>
    /// Configures the database context options for the application.
    /// </summary>
    /// <param name="optionsBuilder">
    /// An instance of <see cref="DbContextOptionsBuilder"/> used to configure the database context.
    /// </param>
    /// <remarks>
    /// This method sets up the SQLite connection string, enables sensitive data logging in development
    /// environments, and configures logging of database commands to a file.
    /// </remarks>
    /// <seealso cref="DbContext.OnConfiguring(DbContextOptionsBuilder)"/>
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // Configure SQLite connection
        optionsBuilder.UseSqlite(AppConnections.Instance.MainConnection);

        // Enable sensitive data logging only in Development environment
        if (Debugger.IsAttached)
        {
            optionsBuilder.EnableSensitiveDataLogging();
            
            if (ContextSettings.Instance.UseAuditInterceptor)
            {
                optionsBuilder.AddInterceptors(new AuditInterceptor());
            }
        }

        // Log database commands to file
        optionsBuilder.LogTo(new DbContextToFileLogger().Log,
            new[] { DbLoggerCategory.Database.Command.Name }, LogLevel.Information);

    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Categories>(entity =>
        {
            entity.HasKey(e => e.CategoryID);

            entity.Property(e => e.CategoryName)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(15)");
            entity.Property(e => e.Description)
                .UseCollation("NOCASE")
                .HasColumnType("text(1073741823)");
            entity.Property(e => e.Picture).HasColumnType("blob(2147483647)");
        });

        modelBuilder.Entity<ContactDevices>(entity =>
        {
            entity.HasKey(e => e.ContactDeviceId);

            entity.HasIndex(e => e.ContactId, "ContactDevices_IX_ContactDevices_ContactId").IsDescending();

            entity.HasIndex(e => e.PhoneTypeIdentifier, "ContactDevices_IX_ContactDevices_PhoneTypeIdentifier").IsDescending();

            entity.Property(e => e.PhoneNumber)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar");

            entity.HasOne(d => d.Contact).WithMany(p => p.ContactDevices).HasForeignKey(d => d.ContactId);

            entity.HasOne(d => d.PhoneTypeIdentifierNavigation).WithMany(p => p.ContactDevices).HasForeignKey(d => d.PhoneTypeIdentifier);
        });

        modelBuilder.Entity<ContactType>(entity =>
        {
            entity.HasKey(e => e.ContactTypeIdentifier);

            entity.Property(e => e.ContactTitle)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar");
        });

        modelBuilder.Entity<Contacts>(entity =>
        {
            entity.HasKey(e => e.ContactId);

            entity.HasIndex(e => e.ContactTypeIdentifier, "Contacts_IX_Contacts_ContactTypeIdentifier").IsDescending();

            entity.Property(e => e.FirstName)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar");
            entity.Property(e => e.FullName)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar");
            entity.Property(e => e.LastName)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar");

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Contacts).HasForeignKey(d => d.ContactTypeIdentifier);
        });

        modelBuilder.Entity<Countries>(entity =>
        {
            entity.HasKey(e => e.CountryIdentifier);

            entity.Property(e => e.Name)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar");
        });

        modelBuilder.Entity<Customers>(entity =>
        {
            entity.HasKey(e => e.CustomerIdentifier);

            entity.HasIndex(e => e.City, "Customers_City").IsDescending();

            entity.HasIndex(e => e.CompanyName, "Customers_CompanyName").IsDescending();

            entity.HasIndex(e => e.ContactId, "Customers_IX_Customers_ContactId").IsDescending();

            entity.HasIndex(e => e.ContactTypeIdentifier, "Customers_IX_Customers_ContactTypeIdentifier").IsDescending();

            entity.HasIndex(e => e.CountryIdentifier, "Customers_IX_Customers_CountryIdentifier").IsDescending();

            entity.HasIndex(e => e.PostalCode, "Customers_PostalCode").IsDescending();

            //entity.HasIndex(e => e.Region, "Customers_Region").IsDescending();

            entity.Property(e => e.City)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(15)");
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(40)");

            //entity.Property(e => e.Fax)
            //    .UseCollation("NOCASE")
            //    .HasColumnType("nvarchar(24)");

            entity.Property(e => e.ModifiedDate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.Phone)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(24)");
            entity.Property(e => e.PostalCode)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(10)");

            //entity.Property(e => e.Region)
            //    .UseCollation("NOCASE")
            //    .HasColumnType("nvarchar(15)");

            entity.Property(e => e.Street)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(60)");

            entity.HasOne(d => d.Contact).WithMany(p => p.Customers).HasForeignKey(d => d.ContactId);

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Customers).HasForeignKey(d => d.ContactTypeIdentifier);

            entity.HasOne(d => d.CountryIdentifierNavigation).WithMany(p => p.Customers).HasForeignKey(d => d.CountryIdentifier);

        });

        modelBuilder.Entity<Employees>(entity =>
        {
            entity.HasKey(e => e.EmployeeID);

            entity.HasIndex(e => e.ContactTypeIdentifier, "Employees_IX_Employees_ContactTypeIdentifier").IsDescending();

            entity.HasIndex(e => e.CountryIdentifier, "Employees_IX_Employees_CountryIdentifier").IsDescending();

            entity.HasIndex(e => e.ReportsToNavigationEmployeeID, "Employees_IX_Employees_ReportsToNavigationEmployeeID").IsDescending();

            entity.Property(e => e.Address)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(60)");
            entity.Property(e => e.BirthDate).HasColumnType("datetime");
            entity.Property(e => e.City)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(15)");
            entity.Property(e => e.Extension)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(4)");
            entity.Property(e => e.FirstName)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(10)");
            entity.Property(e => e.FullName)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(57)");
            entity.Property(e => e.HireDate).HasColumnType("datetime");
            entity.Property(e => e.HomePhone)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(24)");
            entity.Property(e => e.LastName)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(20)");
            entity.Property(e => e.Notes)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar");
            entity.Property(e => e.PostalCode)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(10)");
            entity.Property(e => e.Region)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(15)");
            entity.Property(e => e.TitleOfCourtesy)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(25)");

            entity.HasOne(d => d.ContactTypeIdentifierNavigation).WithMany(p => p.Employees).HasForeignKey(d => d.ContactTypeIdentifier);

            entity.HasOne(d => d.CountryIdentifierNavigation).WithMany(p => p.Employees).HasForeignKey(d => d.CountryIdentifier);

            entity.HasOne(d => d.ReportsToNavigationEmployee).WithMany(p => p.InverseReportsToNavigationEmployee).HasForeignKey(d => d.ReportsToNavigationEmployeeID);

            entity.HasMany(d => d.Territory).WithMany(p => p.Employee)
                .UsingEntity<Dictionary<string, object>>(
                    "EmployeeTerritories",
                    r => r.HasOne<Territories>().WithMany()
                        .HasForeignKey("TerritoryID")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    l => l.HasOne<Employees>().WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    j =>
                    {
                        j.HasKey("EmployeeID", "TerritoryID");
                        j.HasIndex(new[] { "TerritoryID" }, "EmployeeTerritories_IX_EmployeeTerritories_TerritoryID").IsDescending();
                        j.IndexerProperty<string>("TerritoryID")
                            .UseCollation("NOCASE")
                            .HasColumnType("nvarchar(20)");
                    });
        });

        modelBuilder.Entity<OrderDetails>(entity =>
        {
            entity.HasKey(e => new { e.OrderID, e.ProductID });

            entity.HasIndex(e => e.ProductID, "OrderDetails_IX_OrderDetails_ProductID").IsDescending();

            entity.Property(e => e.Quantity).HasColumnType("smallint");
            entity.Property(e => e.UnitPrice).HasColumnType("numeric");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderID)
                .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductID)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Orders>(entity =>
        {
            entity.HasKey(e => e.OrderID);

            entity.HasIndex(e => e.CustomerIdentifier, "Orders_IX_Orders_CustomerIdentifier").IsDescending();

            entity.HasIndex(e => e.EmployeeID, "Orders_IX_Orders_EmployeeID").IsDescending();

            entity.HasIndex(e => e.ShipVia, "Orders_IX_Orders_ShipVia").IsDescending();

            entity.Property(e => e.DeliveredDate)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.Freight).HasColumnType("numeric");
            entity.Property(e => e.OrderDate)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.RequiredDate)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.ShipAddress)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(60)");
            entity.Property(e => e.ShipCity)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(15)");
            entity.Property(e => e.ShipCountry)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(15)");
            entity.Property(e => e.ShipPostalCode)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(10)");
            entity.Property(e => e.ShipRegion)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(15)");
            entity.Property(e => e.ShippedDate)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");

            entity.HasOne(d => d.CustomerIdentifierNavigation).WithMany(p => p.Orders).HasForeignKey(d => d.CustomerIdentifier);

            entity.HasOne(d => d.Employee).WithMany(p => p.Orders).HasForeignKey(d => d.EmployeeID);

            entity.HasOne(d => d.ShipViaNavigation).WithMany(p => p.Orders).HasForeignKey(d => d.ShipVia);
        });

        modelBuilder.Entity<PhoneType>(entity =>
        {
            entity.HasKey(e => e.PhoneTypeIdenitfier);

            entity.Property(e => e.PhoneTypeDescription)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar");
        });

        modelBuilder.Entity<Products>(entity =>
        {
            entity.HasKey(e => e.ProductID);

            entity.HasIndex(e => e.CategoryID, "Products_IX_Products_CategoryID").IsDescending();

            entity.HasIndex(e => e.SupplierID, "Products_IX_Products_SupplierID").IsDescending();

            entity.Property(e => e.Discontinued).HasColumnType("bit");
            entity.Property(e => e.DiscontinuedDate)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(40)");
            entity.Property(e => e.QuantityPerUnit)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(20)");
            entity.Property(e => e.ReorderLevel).HasColumnType("smallint");
            entity.Property(e => e.UnitPrice).HasColumnType("numeric");
            entity.Property(e => e.UnitsInStock).HasColumnType("smallint");
            entity.Property(e => e.UnitsOnOrder).HasColumnType("smallint");

            entity.HasOne(d => d.Category).WithMany(p => p.Products).HasForeignKey(d => d.CategoryID);

            entity.HasOne(d => d.Supplier).WithMany(p => p.Products).HasForeignKey(d => d.SupplierID);
        });

        modelBuilder.Entity<Region>(entity =>
        {
            entity.Property(e => e.RegionID).ValueGeneratedNever();
            entity.Property(e => e.RegionDescription)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("char(50)");
        });

        modelBuilder.Entity<Shippers>(entity =>
        {
            entity.HasKey(e => e.ShipperID);

            entity.Property(e => e.ShipperID).ValueGeneratedNever();
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(40)");
            entity.Property(e => e.Phone)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(24)");
        });

        modelBuilder.Entity<SupplierRegion>(entity =>
        {
            entity.HasKey(e => e.RegionId);

            entity.Property(e => e.RegionDescription)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar");
        });

        modelBuilder.Entity<Suppliers>(entity =>
        {
            entity.HasKey(e => e.SupplierID);

            entity.HasIndex(e => e.CountryIdentifier, "Suppliers_IX_Suppliers_CountryIdentifier").IsDescending();

            entity.Property(e => e.City)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(15)");
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(40)");
            entity.Property(e => e.ContactName)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(30)");
            entity.Property(e => e.ContactTitle)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(30)");
            entity.Property(e => e.Fax)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(24)");
            entity.Property(e => e.HomePage)
                .UseCollation("NOCASE")
                .HasColumnType("text(1073741823)");
            entity.Property(e => e.Phone)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(24)");
            entity.Property(e => e.PostalCode)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(10)");
            entity.Property(e => e.Region)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(15)");
            entity.Property(e => e.Street)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(60)");

            entity.HasOne(d => d.CountryIdentifierNavigation).WithMany(p => p.Suppliers).HasForeignKey(d => d.CountryIdentifier);

            entity.HasOne(d => d.RegionNavigation).WithMany(p => p.Suppliers)
                .HasForeignKey(d => d.RegionId)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        modelBuilder.Entity<Territories>(entity =>
        {
            entity.HasKey(e => e.TerritoryID);

            entity.HasIndex(e => e.RegionID, "Territories_IX_Territories_RegionID").IsDescending();

            entity.Property(e => e.TerritoryID)
                .UseCollation("NOCASE")
                .HasColumnType("nvarchar(20)");
            entity.Property(e => e.TerritoryDescription)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("char(50)");

            entity.HasOne(d => d.Region).WithMany(p => p.Territories)
                .HasForeignKey(d => d.RegionID)
                .OnDelete(DeleteBehavior.ClientSetNull);
        });

        if (ContextSettings.Instance.CustomerOptions.UseQueryFilter)
        {

            var cust = new Customers(); // for nameof operator

            modelBuilder.Entity<Customers>()
                .HasQueryFilter(c =>
                    EF.Property<int?>(c, nameof(cust.CountryIdentifier)) == 20); // USA
        }

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}